platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/QianyuImComponent/QYPodsSpecs.git'

target 'QYVideoModule_Example' do
  pod 'QYVideoModule', :path => '../'

  
end
